<?php
if(!$wpdb)
{
    @require('../../../wp-config.php');
}
if(!$wpdb)
{
    echo 'WP Database not available. Quitting';
    die;
}
global $wpdb;
include 'tagthis_core.php';

$tt_display=get_option("tt_display");
$tt_spamstrength=get_option("tt_spamstrength");
$tt_customcss=get_option("tt_customcss");
$tt_
?>
<div class="wrap">
<h2>Tag This Options
<form action="<?php echo $url ?>" method="post" >
<h3>Display?</h3>
<select name="tt_display">
<option value="1" <?php if($tt_display==1) echo "selected=\"True\""; ?>>Yes</option>
<option value="0" <?php if($tt_display==0) echo "selected=\"True\""; ?>>No</option>
</select>
<h3>Custom CSS?</h3>
Add custom style rules to the tagthis widget<br>
<textarea rows="8" columns="50">
<?php echo $tt_customcss; ?>
</textarea>
<h3>Spam Protection Strength</h3>
<strong>Regular:</strong> Flags a tag as spam if it matches only the list of blacklisted tags.<br><br>
<strong>Extra:</strong> Flags a tag as spam if the text matches the blacklisted tags or the IP matches the blacklisted IPs (not recommended)<br>

<select name="tt_display">
<option value="1" <?php if($tt_display==1) echo "selected=\"True\""; ?>>Regular</option>
<option value="0" <?php if($tt_display==0) echo "selected=\"True\""; ?>>Extra</option>
</select>
<br>
<input type="submit" name="update2" value="UPDATE">
</form>


</div>
<?php
require('framework.php');
//using framework for a plugin
//create a new updater object
$updater=new ocframework();
//set the versionpath, pointing to a remote textfile containing only the latest version
$updater->versionpath='http://yourdomain.com/update.txt';
//note that this text file can also be generated by a html file or php file but it must have only THE VERSION and nothing else. no other output. The framework copmares the text in the file and the version string
//set the current version of the plugin. Be sure to update the version when you update the plugin
$updater->version='0.1';
//set the path of the zip file to be downloaded
$updater->downloadpath='http://yourdomain.com/plugin.zip';
if($updater->checkForUpdate())
{
	$updater->update();
}?>